### ISSUE TITLE
Home Page Description not responsive

### ISSUE THREAD

**Issue by khaledadrani** [RiadhAdrani/slick-portfolio-svelte#1]
When I change the size of the screen, the description won't adapt.

**Comment by RiadhAdrani** [comment]
Problem with `mozilla` not supporting `-webkit-fill-available` property.
Solved by adding correct css properties [here](https://github.com/RiadhAdrani/slick-portfolio-svelte/blob/b4ee8d876e1e25d1996e56d0339c00d208b2511f/src/routes/%2Blayout.svelte#L35).
