### ISSUE TITLE
404 Github page

### ISSUE THREAD

**Issue by Honsl** [RiadhAdrani/slick-portfolio-svelte#12]
I have cloned the repository and made the listed changes, but I am getting a 404 .

https://github.com/Honsl/Honsl.github.io

> make sure to enable github actions with the correct permissions :
go to your repo Settings > Actions > General :
Actions permissions : check Allow all actions and reusable workflows
Workflow permissions : check Read repository contents and packages permissions
you cloned the repo with main as the main branch, change the target branch in [deploy.yml](https://github.com/RiadhAdrani/slick-portfolio-svelte/blob/31bc1621009c60d77ef197b420a18b2f996876a9/.github/workflows/deploy.yml#L5) to main.
push changes to run the action with new settings and permissions, or create an empty commit and push it if you didn't change anything.
enable GitHub Pages deployment on the newly created gh-pages branch:
go to your repo's Settings > Pages
Source : select Deploy from a branch
Branch : select gh-pages and / (root) and click on save
wait for the page to be deployed

**Comment by RiadhAdrani** [comment]
Hello,
Can in your `svelte.config.js`, try to set the url base to just an empty string `const base = "";` and let me know if the problem still persist.

**Comment by Honsl** [comment]
Hi,
 Thank you for taking a look at it. I have made the change, but it is still showing the 404.

**Comment by RiadhAdrani** [comment]
Hello, it's working : https://honsl.github.io/

**Comment by Honsl** [comment]
Thank you, the other issue was with the custom domain.
