### ISSUE TITLE
Certain Elements are in wrong theme on initial load

### ISSUE THREAD

**Issue by alessioamo** [RiadhAdrani/slick-portfolio-svelte#13]
If you load the website for the first time (you can test this by opening it in an incognito page) certain elements are in the wrong theme. For example, the title text on the main page is in white instead of black. This can be fixed by changing the theme from dark and back to light but on initial load the issue still persists.
![image](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/80137378/bb9c6ffb-7ea1-4866-a64e-958bb581cbc6)
Image with title highlighted to show it's there
![image](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/80137378/dfb1663e-3afe-4958-938b-acee81c22c87)

**Comment by Honsl** [comment]
This seems to happen on the skills page also, it does not load the colors or logos - until you switch to dark mode
![image](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/6414112/ffadbc14-b678-4981-a175-3c314f2125dc)
![image](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/6414112/95831b54-8773-4e5d-ab97-a57029f6682f)

**Comment by RiadhAdrani** [comment]
hello @alessioamo, It works fine on my end (edge chromium, even in incognito), which browser are you using ?

**Comment by Honsl** [comment]
Edge

**Comment by RiadhAdrani** [comment]
> Edge

Is that in development or in production (if so can you provide a link)

**Comment by Honsl** [comment]
production - ryanhonsl.ca

**Comment by Honsl** [comment]
production  - [https://honsl.github.io/](https://honsl.github.io/)

**Comment by RiadhAdrani** [comment]
Weird, it is working on my machine, maybe it could be issues related to network ?

**Comment by alessioamo** [comment]
I have tried using Edge and Chrome and the issue persists on both browsers. I even had someone else test it on their PC and the same thing happens. When I open @Honsl 's page, I see the same issue as well

**Comment by RiadhAdrani** [comment]
Very weird, 
I too tried with multiple machines (3) and it is working as intended :
![Screenshot from 2024-01-16 20-16-21](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/54232641/9144edae-73fe-4cef-a854-f9204e53ca88)

to narrow the scope, the problem occurs only with the light mode ?

**Comment by Honsl** [comment]
Seems to be only on light mode and on the initial visit to the site (you need to change to dark mode for it to be able to show on next visit). Visiting the site in incognito always has the issue.

**Comment by alessioamo** [comment]
That's the same issue for me

**Comment by alessioamo** [comment]
@Honsl have you been able to find a solution?

**Comment by RiadhAdrani** [comment]
> @Honsl have you been able to find a solution?
> 

Hello,
I am busy with work, I'll have a look at it in the weekend hopefully.

**Comment by RiadhAdrani** [comment]
Hello again,
any update on your end ? I was unable to reproduce the bug ?
otherwise, maybe we can toggle the theme (twice) on startup and display a loading spinner, for now until we find the culprit.

**Comment by alessioamo** [comment]
I was unable to find a reason for the bug or a solution to it. I was thinking of doing what you said and toggle the theme twice on startup as a temporary fix

**Comment by RiadhAdrani** [comment]
Hello, @alessioamo @Honsl
let us know if the new commits fixed the issue.

**Comment by alessioamo** [comment]
Yes it does!

**Comment by Honsl** [comment]
It does load the text and images now, but on initial load it now does this weird page load - were everything is miss sized.

https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/6414112/7144b881-6496-4e84-a700-d7489f41219b

**Comment by RiadhAdrani** [comment]
@Honsl I think that has to do with the amount of files/data the page is loading
