### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by ghost** [RiadhAdrani/slick-portfolio-svelte#15]
Does the website have mobile suport? I tried opening on my Samsung A34 5G, and it does not look centered.
![Screenshot_20240119_092443_Chrome](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/65186852/909edfd8-cb4d-477b-b18f-fde44c69111c)

Just curious haha.

**Comment by RiadhAdrani** [comment]
It does, but I recently added other pages to the navbar and it overflowed, will be fixing soon.
