### ISSUE TITLE
No Workflow Launch

### ISSUE THREAD

**Issue by MJ-Peters** [RiadhAdrani/slick-portfolio-svelte#18]
Hiya, for some reason I can't get anything to launch. I'm just getting a plain white screen. I'm probably doing something very obviously wrong, but I'm new to this so can't spot it. It would be great if you could help, thank you!

https://github.com/MJ-Peters/Developer-Portfolio

**Comment by RiadhAdrani** [comment]
Hello, 
set your base [here](https://github.com/MJ-Peters/Developer-Portfolio/blob/3b7587891fd54ad707cd760d5f494568e455b063/svelte.config.js#L4) to  `/Developer-Portfolio`, which is the name of your repo, and let me know if it worked.

**Comment by MJ-Peters** [comment]
Thank you! I completely misunderstood the purpose of the base line of code. All is working now, have a great day!

**Comment by MJ-Peters** [comment]
I do have one last question if you don't mind. Is there a way for me to preview the webpage while building it in VS Code or is it necessary to push to github and deploy to pages each time you want to see the whole thing?

**Comment by RiadhAdrani** [comment]
Hello again,
the closest thing that I can think of is running both `yarn build` and then `yarn preview`, which in the end will create a production build and preview it. However, the problem that you mentioned earlier won't occur in the preview because it is related to file fetching and an invalid URL generated from the base.

**Comment by MJ-Peters** [comment]
Thank you!

**Comment by TraFost** [comment]
the same thing happened to me and i already set the base variable to my repo branch, but it still showing blank white page, please help

https://github.com/TraFost/personal-profile
