### ISSUE TITLE
More Technologies

### ISSUE THREAD

**Issue by RiadhAdrani** [RiadhAdrani/slick-portfolio-svelte#2]
Here's a list of more technologies, any suggestion is welcome:
- Django
- Docker
- Kubernetes
- FastApi
- Flask
- AWS
- Bootstrap
- Rust
- Go
- C
- C++

**Comment by khaledadrani** [comment]
* pandas
* numpy
* nginx
* apache server
* apache kafka
* redis
* celery
* rabbitQ
* Postgresql
* Oracle DB
* MongdoDB
* Neo4j
* SqlAlchemy
* Alembic
* Aiohttp
* Beautiful Soup
* Selenium
* Scrapy
