### ISSUE TITLE
I cant get the gh-pages branch

### ISSUE THREAD

**Issue by bigpaloma** [RiadhAdrani/slick-portfolio-svelte#23]
i cloned the repo, do i create this branch myself or what exactly do i need to do. when i visit my page it just shows me the readme from the gihub main branch

**Comment by bigpaloma** [comment]
I added the branch manually and then cloned your gh branch into mine, selected it in settings/pages. now i get this error and it still just shows me the readme page when i go on to the site
![Capture](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/117634763/c1a2986d-6d29-4be7-bf46-71cdba26eacc)

**Comment by RiadhAdrani** [comment]
Hello, 
Just curious, have you followed the `README.md` file ? and did you face any problems with it ?

The `gh-pages` is automatically generated by [this](https://github.com/RiadhAdrani/slick-portfolio-svelte/blob/master/.github/workflows/deploy.yml) workflow. 

By the way, I visited your GitHub and I saw that your default branch is set to `main`, so, change [`master`](https://github.com/RiadhAdrani/slick-portfolio-svelte/blob/d0dd64b2ea7db0500b9d4d1cd4773a62a3d47667/.github/workflows/deploy.yml#L5) to `main` in the workflow.

Let me know if this fixed your problem.
