### ISSUE TITLE
Different colors for different titles

### ISSUE THREAD

**Issue by Sam-Akla** [RiadhAdrani/slick-portfolio-svelte#27]
Hi, I would like to have different colors for different maintitles, such as projects, skills, etc.

Below is the image of different colors for the navbar. I would like to have same colors for each maintitle. I have checked in MainTitle.svelte file and was able to change for all the titles one color. I am not sure how to have different colors for different titles. 

I have no background in svelte, therefore any help is appreciated. 

Thanks!

![Screenshot from 2024-02-25 00-25-49](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/31549730/7eb2fe9e-491c-43f2-8e1f-a0dfdeb1526a)

**Comment by RiadhAdrani** [comment]
Hello,
Something like this ? 
![image](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/54232641/d8235f21-cce1-4d28-abbb-d8b68d80149a)
![image](https://github.com/RiadhAdrani/slick-portfolio-svelte/assets/54232641/d9669ec2-f27a-4790-9b5a-1caad91d575e)

if so, check this [`pull request`](https://github.com/Srm-Akla/srm-akla.github.io/pull/1), pull the repo and check if everything is alright and if so, merge it.

**Comment by Sam-Akla** [comment]
Awesome! Thank you!
