### ISSUE TITLE
Website not deploying

### ISSUE THREAD

**Issue by Sam-Akla** [RiadhAdrani/slick-portfolio-svelte#29]
Hi, I did everything mentioned in the README file, and my website is not deploying. 

**Repo**: https://github.com/srm-akla/srm-akla.github.io

Thanks!

**Comment by RiadhAdrani** [comment]
Hi again,
change this [`line`](https://github.com/Srm-Akla/srm-akla.github.io/blob/a2b059ec72ff9e65f85e398c2d4100257ac54dba/svelte.config.js#L4) to `const base = ""`, just an empty base, and let me know if there is another problem.

**Comment by Sam-Akla** [comment]
That works! Thank you! Can you explain why that worked? Very new to web development here :smiley:

**Comment by RiadhAdrani** [comment]
Well, it is not about web development for this case, the repo you are building from is a special repo, it is considered like a domain repo by github, so the base is not needed, not your fault.

if you check my personal portfolio https://riadhadrani.github.io/RiadhAdrani , deployed from this repo https://github.com/RiadhAdrani/RiadhAdrani , I needed to add `/RiadhAdrani` as a base:

`https://` `riadhadrani.github.io` `/RiadhAdrani`

1. protocol
2. domain
3. base

Not very good at explaining, but I hope you got it !

Best wishes.

**Comment by Sam-Akla** [comment]
Yeah, that makes sense! Thanks! And thank you for building an awesome portfolio!
