### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by kgt0205** [RiadhAdrani/slick-portfolio-svelte#3]
I am still a student.
If you want to use this template and release it to people, you will have to do it while receiving server fees through advertisements.
Would it be okay if I put ads in this template?

**Comment by RiadhAdrani** [comment]
Hello,
I didn't exactly get your question, do you want me to commercialize this template or are you asking for permission to put ads in your version of the portfolio ? 

In any case, you can use this template however you like.

Cheers
