### ISSUE TITLE
Feature Request: Multiple section for skills

### ISSUE THREAD

**Issue by Sam-Akla** [RiadhAdrani/slick-portfolio-svelte#30]
Hello, 

I would like to request a feature, which is having multiple sections for skills.  The idea is to having multiple sections such that I can organize skills - Programming languages, Libraries, Softwares, Soft skills, etc.

**Comment by RiadhAdrani** [comment]
Hello,
I added an optional category field for skills, you can check out the result here : https://riadhadrani.github.io/RiadhAdrani/skills
