### ISSUE TITLE
Where to place sitemap.xml for indexing?

### ISSUE THREAD

**Issue by alessioamo** [RiadhAdrani/slick-portfolio-svelte#38]
I am trying to index my website with Google and I need to place a sitemap.xml file in my folder however I have tried in many places and none seem to work. I have tried in the base folder, in the src folder, in a public folder in the src folder and in a public folder in the base folder. I am not sure where to place the file and would appreciate some help.
Thank you

**Comment by RiadhAdrani** [comment]
Hello,
I am not good with SEO, but I will check it out the weekend.
