### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by itsmarcdelacruz** [RiadhAdrani/slick-portfolio-svelte#4]
How would I go about changing
const gh = (file: string) =>
	`https://raw.githubusercontent.com/RiadhAdrani/slick-portfolio-svelte/assets/logos/${file}`;
	
to be able to add my own assets through my own folder instead of going through and pulling the raw githubusercontent?

**Comment by RiadhAdrani** [comment]
Hello,
In [Assets.ts](https://github.com/RiadhAdrani/slick-portfolio-svelte/blob/master/src/lib/data/assets.ts), you can add another entry to the `Assets` record, let's say you need a logo, you can import it and add it like this:

```ts

import myLogo from "$lib/path/to/logo";

// ...

const Assets = {
        MyLogo: myLogo,
	AWS: a('aws.svg'),
	Bootstrap: a('bootstrap.svg'),
	C: a('c.svg'),
	// ...
};
```

if your logo have a dark and a light versions:

```ts
import myLogoDark from "$lib/path/to/logo";
import myLogoLight from "$lib/path/to/logo";

// ...

const Assets = {
        MyLogo: {
             dark: myLogoDark,
             light: myLogoLight,
        },
	AWS: a('aws.svg'),
	Bootstrap: a('bootstrap.svg'),
	C: a('c.svg'),
	// ...
};
```

**Comment by Bram1903** [comment]
Hey @itsmarcdelacruz,

I wanted to bring your attention to my recent Pull Request, #5.

### What's New
In this PR, I've introduced a new directory within the `static` folder called `logos`. This addition will make it easier for you to include additional logos and reference them just like the rest of the logos are currently being referenced.

### Example Usage
To include a custom logo, you can now use the following code:

```typescript
const Assets = {
	AWS: a('aws.svg'),
	CustomLogo: a('customlogo.svg'),
	// ...
};
```

To make this work, all you need to do is place your custom logo file in the `static/logos` directory with the correct naming.
In this case `customlogo.svg`.

I hope this helps!

Kind regards,
Bram

**Comment by itsmarcdelacruz** [comment]
Hey, thanks for mentioning this to me. I actually figured out logos and
stuff afterwards and added and education section for mine. here it is @
mdelacruz.dev
the only issue is sometimes it bugs out with extra buttons for the top menu
bar

**Comment by itsmarcdelacruz** [comment]
The issue for the menu symbols bugging out sometimes is only on mobile by
the way but I haven't tried to figure out what the issue is yet.
