### ISSUE TITLE
Fix carrousel index

### ISSUE THREAD

**Issue by jeroen2002** [RiadhAdrani/slick-portfolio-svelte#40]
When on the homepage and clicking through the carrousel. It ends on te last two images when clicking on the arrow instead of going to the first image.

I have the solution here (Carrousel.svelte starting at line 25):
```javascript
const slide = (right: boolean) => {
		if (right) {
			if (index < items.length - 1) {
				index++;
			} else {
				index = 0;
			}
		} else {
			if (index > 0) {
				index--;
			} else {
				index = items.length - 1;
			}
		}
	};
```

I also think you can get rid of the "toRight" variable.

**Comment by RiadhAdrani** [comment]
Hello, 
I programmed it that way, when it reaches the last item, it go back from end to start: `1 -> 2 -> 3 -> 4 -> 3 -> 2 -> 1`.
Feel free update it in your own portfolio with what you want and need.
