### ISSUE TITLE
easy way to clone the project

### ISSUE THREAD

**Issue by mino9421** [RiadhAdrani/slick-portfolio-svelte#42]
use degit tool made by Rich Harris

#[degit](https://github.com/Rich-Harris/degit)

use this command
degit RiadhAdrani/slick-portfolio-svelte

**Comment by mino9421** [comment]
since its gaining popularity, my suggestion is to add the command to the readme section to help visitors.
looking forward in helping refining this template, I loved it and gonna be using it for myself too.

**Comment by RiadhAdrani** [comment]
Hey @mino9421,
Just updated the readme, check it out and let me know what you think.
