### ISSUE TITLE
Website Deployed Without Styles: CSS and JS Files Not Loaded Despite '.nojekyll' File

### ISSUE THREAD

**Issue by seifeddinerezgui** [RiadhAdrani/slick-portfolio-svelte#45]
### Description

After deploying my website using the Svelte portfolio template, I encountered an issue where the site is deployed without styles. It seems that the CSS and JS files referenced in the `index.html` file inside the `build` directory are not being loaded properly, even after I created the `.nojekyll` file within the `build` directory.

### my website link:
[https://seifeddinerezgui.github.io/MyPortfolio/](url)
Notice that the deployed site is missing styles, and the browser console shows that the CSS and JS files are not being loaded.

### my Repo link:
[https://github.com/seifeddinerezgui/MyPortfolio.git](url)

### What I Tried
- I added a `.nojekyll` file inside the `build` directory to prevent GitHub Pages from ignoring files starting with an underscore (`_`).
- Despite this, the CSS and JS files are still not being read by the browser.

### Screenshots : 
![image](https://github.com/user-attachments/assets/4a9e70fd-9ee9-44f8-890d-c21de26448a6)

**Comment by RiadhAdrani** [comment]
Hello @seifeddinerezgui ,
Just checked out your repo, you didn't activate the github workflow as I mentioned in the readme ?
I noticed there is no `.nojekyll` file in the `gh-pages` files.
Follow [these steps](https://github.com/RiadhAdrani/slick-portfolio-svelte/tree/master?tab=readme-ov-file#deploy-to-github-pages) and let me know if it didn't work.

**Comment by seifeddinerezgui** [comment]
it worked , thank you so much bro , i feel proud you are tunisian 👍  , **big uppp** 💯 
 [https://seifeddinerezgui.github.io/MyPortfolio](url)

**Comment by RiadhAdrani** [comment]
You are welcome ❤️
