### ISSUE TITLE
Getting the readme and not the portfolio

### ISSUE THREAD

**Issue by Loocist23** [RiadhAdrani/slick-portfolio-svelte#48]
Hello,

I encountered an issue similar to what others have experienced. When I push the repository, the workflow runs successfully, but it doesn't create the gh-pages branch. The build happens from the master branch, and I have the master branch present, so I'm not sure what could be the problem.

Thank you for this template! I've also learned a lot about Svelte from using it.

**Comment by RiadhAdrani** [comment]
Bonjour,

I saw that you deleted the `gh-pages`, which is the one containing the built files. Did you follow the mentioned steps regarding permissions for github pages ? if not, apply them, push a commit, which will automatically create the gh-pages  branch and then set it as the source branch (you may need to push another commit) , and that should work.

![Screenshot from 2024-10-04 06-08-20](https://github.com/user-attachments/assets/e8d13c00-3f69-4e8e-a8d9-cb7c32d465f1)

**Comment by Loocist23** [comment]
i did everything you said but the workflow don't create the gh-page branch

![image](https://github.com/user-attachments/assets/e846c952-7e32-44c5-b37c-8a2f5bc16c70)

**Comment by Loocist23** [comment]
ok so i i did it 

i just created the gh-pages branch deleted everything in it and put the build i have done in local
