### ISSUE TITLE
Getting a white blank page

### ISSUE THREAD

**Issue by janzzend** [RiadhAdrani/slick-portfolio-svelte#49]
Hi Riadh! 

I have deployed your amazing template to my GitHub pages, however, I'm getting a white blank page instead. Would you mind checking my repository if what I did wrong? Thank you so much.

My repo: https://github.com/janzzend/janzzend.github.io
My website: https://janzzen.dev/janzzend

**Comment by RiadhAdrani** [comment]
Hey,

Try changing the base in `svelte.config.js` to an empty string like in [here](https://github.com/RiadhAdrani/slick-portfolio-svelte/issues/29) (+ explanation ), should fix it.

And thanks for the compliment.
