### ISSUE TITLE
Only getting ReadMe upon deployment

### ISSUE THREAD

**Issue by iadcruz** [RiadhAdrani/slick-portfolio-svelte#50]
I followed the instructions in the ReadMe and landed up only seeing the ReadMe upon deployment. I then looked through some of the older issues and changed my base to be "". I can't seem to figure out what's wrong. 

Repo: https://github.com/iadcruz/iadcruz.github.io

**Comment by RiadhAdrani** [comment]
Hello @iadcruz ,
It seems that you didn't activate github pages, check these [steps](https://github.com/RiadhAdrani/slick-portfolio-svelte?tab=readme-ov-file#deploy-to-github-pages) .

**Comment by iadcruz** [comment]
I'm not sure I understand as I followed those steps already. I would appreciate any help you could provide.

**Comment by RiadhAdrani** [comment]
@iadcruz 

I am seeing that you still have problems, is this how your options look in `Actions` and `Pages`

![image](https://github.com/user-attachments/assets/ba20b15a-e3ca-42cd-827d-6af4eb9e8922)

![image](https://github.com/user-attachments/assets/299e1c71-623a-40a1-bfb9-cb855a5df3bc)

**Comment by iadcruz** [comment]
That's correct. I am able to run it locally and everything looks amazing, but with Github Pages I get a blank page.

**Comment by RiadhAdrani** [comment]
Hello @iadcruz ,
Can you delete the repo and re-fork pulling only the `master` branch?

**Comment by iadcruz** [comment]
I deleted the repo and re-forked pulling only the master branch, but I am still only getting the ReadMe

**Comment by RiadhAdrani** [comment]
Delete the gh-pages branch, make sure all the options are set up correctly and push another commit to master.

**Comment by RiadhAdrani** [comment]
Hello @iadcruz ,
I updated the readme with more screenshots and details, if you want to have another try.

**Comment by iadcruz** [comment]
If I'm creating a special repository (username.github.io), should I still be seeing gh-pages being created? It is not showing up when I select Deploy from a Branch. With the new ReadMe, should any changes be made to the deploy.yml file? Thanks in advance.

**Comment by RiadhAdrani** [comment]
For forked repository, you need to go to actions and activate any existing workflow. then you need to push to trigger the workflow which will create the `gh-pages`, then you need to activate github pages and set it to build from the branch.
