### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by ceSamet** [RiadhAdrani/slick-portfolio-svelte#51]
Firstly, great job on the website! It looks amazing.

 However, I couldn't manage to deploy it successfully. I followed the instructions in the README file, and I updated the base parameter with my own repository name, but it didn't work. I also tried leaving it empty, as you've suggested for other issues (""), but I still couldn't get it to work. 

Could you please help me with this?

**Comment by RiadhAdrani** [comment]
Hello @ceSamet,
I was very busy this week, I updated the readme with more screenshots and details, if you want to have another try.
