### ISSUE TITLE
Migration to Svelte 5

### ISSUE THREAD

**Issue by hexahigh** [RiadhAdrani/slick-portfolio-svelte#56]
Hey, great website! I'm trying to use it as a template for my new portfolio but I need to use Svelte 5 as many of my libraries no longer support Svelte 4.
I tried using the official migration tool from the Svelte team but it introduced a few annoying bugs which I was unable to resolve, mainly because I'm not good at working on code other people have written.
I could probably help with some parts of the migration.

**Comment by RiadhAdrani** [comment]
Hello @hexahigh ,
I am thinking of that too, maybe even rewriting using shadcn-svelte as ui library. Waiting for the framework to stabilize a little bit, as of now i am seeing a lot of releases from them latelty.

**Comment by RiadhAdrani** [comment]
Hey @hexahigh ,
The re-write is done, check it out [here](https://riadhadrani.github.io/slick-portfolio-svelte-5/) and let me know if there is something missing.

**Comment by hexahigh** [comment]
That was quick! Everything looks good. Although, I preferred the old, more compact navbar, could you maybe add a config option to switch to the old one? **::)**

**Comment by hexahigh** [comment]
Also, how are you handling darkmode? The delay between loading the page and the theme getting applied is quite big.
Edit: Nevermind, I tried various methods to improve it but they didn't work.

**Comment by RiadhAdrani** [comment]
@hexahigh 
I updated the colors to be more neutral, it is the closest that we can get to the old version.

**Comment by hexahigh** [comment]
Just wondering, are you planning on merging the new repo with this one or will they be separated?

**Comment by RiadhAdrani** [comment]
I am not sure really sure. Maybe I will create a new branch for `svelte-4` for the old one and merge the new one with master.

**Comment by RiadhAdrani** [comment]
Hey @hexahigh,
I decided that this repo will hold the svelte-4 version and I added a link in the readme for people who wants the newer version.
